rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  email:
    - licensefinder@pivotallabs.com
  webhooks:
    urls:
    - http://pulse.pivotallabs.com/projects/657d35b7-b896-4bf3-8837-9d558e2ab651/status
    on_start: true
