platform: linux

image_resource:
  type: docker-image
  source:
    repository: licensefinder/license_finder
    tag: latest

inputs:
- name: PR

run:
  path: ./PR/ci/scripts/test.sh

params:
  RUBY_VERSION: