platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource
    tag: 2935e6658db2ab4197b1f888f340d7217c4c8559

inputs:
- name: LicenseFinder

run:
  path: ./LicenseFinder/ci/scripts/containerize-tests.sh

params:
  RUBY_VERSION_UNDER_TEST:
