---
image_resource:
  type: docker-image
  source:
    repository: licensefinder/license_finder
    tag: latest
platform: linux
inputs:
- name: lf-git
- name: lf-release
outputs:
- name: version
caches:
- path: lf-git/CHANGELOG.md
run:
  path: lf-git/ci/scripts/updateChangelog.sh